### ISSUE TITLE
Instructions in Readme don't work.

### ISSUE THREAD

**Issue by MicahZoltu** [mrdjohnson/llm-x#16]
Upon doing `yarn install` and telling corepack to install yarn 4.1.1, it fails with:
```
Internal Error: ENOENT: no such file or directory, stat '/workspace/.yarn/releases/yarn-4.1.1.cjs'
Error: ENOENT: no such file or directory, stat '/workspace/.yarn/releases/yarn-4.1.1.cjs'
```

You can work around this by deleting `.yarnrc.yml` and manually installing yarn with `corepack prepare yarn@4.1.1 --activate`, which will allow `yarn install` to complete.

However, when you then run `yarn dev` the following errors appear:
```
Error: The following dependencies are imported but could not be resolved:

  @langchain/core/messages (imported by /workspace/llm-x/src/utils/OllamaApi.ts)
  @langchain/core/prompts (imported by /workspace/llm-x/src/utils/OllamaApi.ts)
  @langchain/core/output_parsers (imported by /workspace/llm-x/src/utils/OllamaApi.ts)

Are they installed?
    at file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:52303:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:51715:38
```

You can reproduce the first problem with a simplified repro case in docker:
```Dockerfile
FROM node:22.1.0
RUN corepack enable
WORKDIR /workspace
RUN echo 'yarnPath: .yarn/releases/yarn-4.1.1.cjs' > /workspace/.yarnrc.yml
RUN echo '{ "packageManager": "yarn@4.1.1" }' > /workspace/package.json
RUN corepack prepare yarn@4.1.1 --activate
RUN yarn install
```
You can reproduce the second problem with the following Dockerfile:
```Dockerfile
FROM node:22.1.0-alpine3.18@sha256:5a4751fb2e95bb0a0ad5ac1f92fd36076c7337b89667e396dbbabf36fa5b1d6f
RUN apk add --no-cache git
RUN corepack enable

WORKDIR /workspace
RUN git clone https://github.com/mrdjohnson/llm-x.git
WORKDIR /workspace/llm-x
RUN rm .yarnrc .yarnrc.yml
RUN corepack prepare yarn@4.1.1 --activate
RUN yarn install

ENTRYPOINT [ "yarn", "dev" ]
```

**Comment by MicahZoltu** [comment]
You can fix the second issue (and the one that comes after it) with `yarn add @langchain/core @nextui-org/theme`.

**Comment by MicahZoltu** [comment]
Unfortunately, it seems there are more errors after that.  The server starts, but as soon as you connect to it from a browser you get this:
```
(node:29) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

🌼   daisyUI 4.7.2
├─ ✔︎ 3 themes added            https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

1:06:38 PM [vite] Internal server error: Failed to resolve import "workbox-window" from "../../@vite-plugin-pwa/virtual:pwa-register/react". Does the file exist?
  Plugin: vite:import-analysis
  File: /@vite-plugin-pwa/virtual:pwa-register/react:29:25
  27 |    async function register() {
  28 |      if ("serviceWorker" in navigator) {
  29 |        wb = await import("workbox-window").then(({ Workbox }) => {
     |                          ^
  30 |          return new Workbox("/llm-x/dev-sw.js?dev-sw", { scope: "/llm-x/", type: "classic" });
  31 |        }).catch((e) => {
      at formatError (file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50545:46)
      at TransformContext.error (file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50539:19)
      at normalizeUrl (file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:65623:33)
      at async file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:65778:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:65699:13)
      at async Object.transform (file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50854:30)
      at async loadAndTransform (file:///workspace/llm-x/.yarn/__virtual__/vite-virtual-5ab3b4ee8a/3/root/.yarn/berry/cache/vite-npm-5.1.5-419c18fcfa-10c0.zip/node_modules/vite/dist/node/chunks/dep-G-px366b.js:53644:29)
1:06:38 PM [vite] Pre-transform error: Failed to resolve import "workbox-window" from "../../@vite-plugin-pwa/virtual:pwa-register/react". Does the file exist?
[vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
32 |      @apply prose-spacing !max-w-full;
33 |
34 |      ul,
   |      ^^^
35 |      ol,
   |  ^^^^^^^
36 |      li {
   |  ^^^^^^^^
37 |        @apply prose-spacing [&>p:first-child]:inline;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
38 |      }
   |  ^^^^^
```

**Comment by mrdjohnson** [comment]
👋  Are you on windows by chance?

**Comment by MicahZoltu** [comment]
I am, though everything is inside of docker running in WSL.  The docker container being used was `node` official (as seen in the repro cases).

**Comment by mrdjohnson** [comment]
I'm looking into this, thanks!

**Comment by mrdjohnson** [comment]
I will be putting out a PR soon, it looks like the actual issue is that I gitignored .yarn/releases

an easy fix is to remove `yarnPath: .yarn/releases/yarn-4.1.1.cjs` from .yarnrc.yml (and maybe remove the .yarnrc file too) after that the other issues go away (they were caused by deleting the .yarnrc.yml file which told yarn to link the node modules which blah blah ) 

thanks for finding this though!! sorry you ended up going down a rabbit hole 😬

**Comment by mrdjohnson** [comment]
I used your docker file to help me verify that the project builds! thanks for that ( i had to run it with --no-cache) 

Another team-member is doing some of the docker set up actually so i'll let them verify the ports and all but I hope this helps you in the meantime!
